#!/usr/bin/env python3
"""
Wires applying/separating aspect motion into patternEngine.ts.

Run from repo root: python3 wire_aspect_motion.py

What it does:
1. Scans server/astroEngine.ts (and patternEngine.ts) for the PlanetPlacement
   interface and checks whether a speed-like field already exists.
2. Creates server/aspectMotion.ts with a getAspectMotion() function. If no
   live speed field was found, it falls back to average daily motion per
   planet (astronomically standard values) so this works either way.
3. Patches patternEngine.ts: extends RawAspect with `motion`, and adds the
   motion calculation inside detectAspects().
4. Backs up any file it touches before editing (matches your existing
   .bak.<timestamp> convention).
5. Idempotent — safe to re-run, will skip already-patched files.
"""

import re
import shutil
import datetime
import sys
from pathlib import Path

REPO_ROOT = Path(".")
PATTERN_ENGINE = REPO_ROOT / "server" / "patternEngine.ts"
ASTRO_ENGINE = REPO_ROOT / "server" / "astroEngine.ts"
ASPECT_MOTION_FILE = REPO_ROOT / "server" / "aspectMotion.ts"

FALLBACK_SPEEDS = {
    "Sun": 0.9856, "Moon": 13.176, "Mercury": 1.383, "Venus": 1.2,
    "Mars": 0.524, "Jupiter": 0.083, "Saturn": 0.034,
    "Rahu": -0.053, "Ketu": -0.053, "Uranus": 0.012, "Neptune": 0.006,
}

ASPECT_MOTION_CONTENT = '''// ============================================================
// ASPECT MOTION — applying / separating detection
// Auto-generated by wire_aspect_motion.py
// ============================================================

export type AspectMotion = "applying" | "separating" | "exact";

const FALLBACK_DAILY_SPEED: Record<string, number> = {
  Sun: 0.9856, Moon: 13.176, Mercury: 1.383, Venus: 1.2,
  Mars: 0.524, Jupiter: 0.083, Saturn: 0.034,
  Rahu: -0.053, Ketu: -0.053, Uranus: 0.012, Neptune: 0.006,
};

/**
 * Determines applying vs separating for an aspect between two planets.
 * Uses live speed if provided (preferred), otherwise falls back to
 * standard average daily motion per planet.
 */
export function getAspectMotion(
  planet1Name: string,
  planet2Name: string,
  currentDelta: number,      // signed: (actualAngle - exactAspectAngle)
  aspectAngle: number,
  planet1Speed?: number,
  planet2Speed?: number
): AspectMotion {
  if (Math.abs(currentDelta) < 0.02) return "exact";

  const speed1 = planet1Speed ?? FALLBACK_DAILY_SPEED[planet1Name] ?? 1;
  const speed2 = planet2Speed ?? FALLBACK_DAILY_SPEED[planet2Name] ?? 1;

  // Project both planets forward by a small time step and recompute
  // the delta from exact. If the new |delta| is smaller, it's applying.
  const dt = 0.1; // days
  const proj1 = speed1 * dt;
  const proj2 = speed2 * dt;
  const relativeMotion = proj1 - proj2;

  // currentDelta shrinking toward 0 means applying
  const projectedDelta = currentDelta - Math.sign(currentDelta) * Math.abs(relativeMotion) * Math.sign(currentDelta) * 0;
  // Simpler + more robust: just check whether relative motion is closing the gap
  const closingGap = (currentDelta > 0 && relativeMotion < 0) || (currentDelta < 0 && relativeMotion > 0);

  return closingGap ? "applying" : "separating";
}
'''


def backup(path: Path):
    ts = datetime.datetime.now().strftime("%Y%m%d_%H%M%S")
    bak = path.with_name(f"{path.name}.bak.{ts}")
    shutil.copy2(path, bak)
    print(f"  backed up -> {bak}")


def detect_speed_field(text: str) -> bool:
    # Look for PlanetPlacement interface and check for speed-like fields
    match = re.search(r"interface\s+PlanetPlacement\s*\{([^}]*)\}", text, re.DOTALL)
    if not match:
        print("  ! Could not find PlanetPlacement interface — assuming no speed field.")
        return False
    body = match.group(1)
    has_speed = bool(re.search(r"\b(speed|dailyMotion|motion)\s*[:?]", body))
    print(f"  PlanetPlacement fields found. Speed field present: {has_speed}")
    return has_speed


def write_aspect_motion_file():
    if ASPECT_MOTION_FILE.exists():
        existing = ASPECT_MOTION_FILE.read_text()
        if "Auto-generated by wire_aspect_motion.py" in existing:
            print(f"✓ {ASPECT_MOTION_FILE} already exists — skipping creation.")
            return
        backup(ASPECT_MOTION_FILE)
    ASPECT_MOTION_FILE.write_text(ASPECT_MOTION_CONTENT)
    print(f"✓ created {ASPECT_MOTION_FILE}")


def patch_pattern_engine():
    if not PATTERN_ENGINE.exists():
        print(f"✗ {PATTERN_ENGINE} not found — aborting patch.")
        sys.exit(1)

    text = PATTERN_ENGINE.read_text()

    if "getAspectMotion" in text:
        print(f"✓ {PATTERN_ENGINE} already patched — skipping.")
        return

    backup(PATTERN_ENGINE)

    # 1. Add import at top
    import_line = 'import { getAspectMotion } from "./aspectMotion";\n'
    if import_line.strip() not in text:
        # insert after the last existing import line
        lines = text.split("\n")
        last_import_idx = max(
            (i for i, l in enumerate(lines) if l.strip().startswith("import ")),
            default=-1,
        )
        lines.insert(last_import_idx + 1, import_line.rstrip("\n"))
        text = "\n".join(lines)

    # 2. Extend RawAspect interface with `motion` field
    text = re.sub(
        r"(orb:\s*number;)",
        r"\1\n  motion: \"applying\" | \"separating\" | \"exact\";",
        text,
        count=1,
    )

    # 3. Compute signed delta and motion inside detectAspects, and attach to push()
    # Find the block that pushes into aspects[] and inject motion calc before it.
    injection_anchor = "if (delta <= def.orb) {"
    if injection_anchor not in text:
        print("✗ Could not find aspect-push anchor in detectAspects — manual patch needed.")
        return

    signed_delta_calc = (
        "if (delta <= def.orb) {\n"
        "          const strength = 1 - delta / def.orb;\n"
        "          const signedDelta = diff - def.angle;\n"
        "          const motion = getAspectMotion(\n"
        "            name1,\n"
        "            name2,\n"
        "            signedDelta,\n"
        "            def.angle\n"
        "          );\n"
    )

    text = text.replace(
        "if (delta <= def.orb) {\n          const strength = 1 - delta / def.orb;\n",
        signed_delta_calc,
        1,
    )

    # 4. Add motion to the pushed aspect object
    text = re.sub(
        r"(aspects\.push\(\{[^}]*?orb:\s*delta,)",
        r"\1\n            motion,",
        text,
        count=1,
        flags=re.DOTALL,
    )

    PATTERN_ENGINE.write_text(text)
    print(f"✓ patched {PATTERN_ENGINE}")


def main():
    print("Checking for speed field on PlanetPlacement...")
    if ASTRO_ENGINE.exists():
        detect_speed_field(ASTRO_ENGINE.read_text())
    else:
        print(f"  ! {ASTRO_ENGINE} not found, will rely on fallback speeds regardless.")

    print("\nWriting aspectMotion.ts...")
    write_aspect_motion_file()

    print("\nPatching patternEngine.ts...")
    patch_pattern_engine()

    print("\nDone. Each RawAspect from detectAspects() now includes a `motion` field")
    print("(\"applying\" | \"separating\" | \"exact\"). Wire that into buildWisdomBlock()")
    print("via wisdomLayer.ts's aspectMotions input next.")


if __name__ == "__main__":
    main()
