// ============================================================
// ASPECT MOTION — applying / separating detection
// Auto-generated by wire_aspect_motion.py
// ============================================================

export type AspectMotion = "applying" | "separating" | "exact";

const FALLBACK_DAILY_SPEED: Record<string, number> = {
  Sun: 0.9856, Moon: 13.176, Mercury: 1.383, Venus: 1.2,
  Mars: 0.524, Jupiter: 0.083, Saturn: 0.034,
  Rahu: -0.053, Ketu: -0.053, Uranus: 0.012, Neptune: 0.006,
};

/**
 * Determines applying vs separating for an aspect between two planets.
 * Uses live speed if provided (preferred), otherwise falls back to
 * standard average daily motion per planet.
 */
export function getAspectMotion(
  planet1Name: string,
  planet2Name: string,
  currentDelta: number,      // signed: (actualAngle - exactAspectAngle)
  aspectAngle: number,
  planet1Speed?: number,
  planet2Speed?: number
): AspectMotion {
  if (Math.abs(currentDelta) < 0.02) return "exact";

  const speed1 = planet1Speed ?? FALLBACK_DAILY_SPEED[planet1Name] ?? 1;
  const speed2 = planet2Speed ?? FALLBACK_DAILY_SPEED[planet2Name] ?? 1;

  // Project both planets forward by a small time step and recompute
  // the delta from exact. If the new |delta| is smaller, it's applying.
  const dt = 0.1; // days
  const proj1 = speed1 * dt;
  const proj2 = speed2 * dt;
  const relativeMotion = proj1 - proj2;

  // currentDelta shrinking toward 0 means applying
  const projectedDelta = currentDelta - Math.sign(currentDelta) * Math.abs(relativeMotion) * Math.sign(currentDelta) * 0;
  // Simpler + more robust: just check whether relative motion is closing the gap
  const closingGap = (currentDelta > 0 && relativeMotion < 0) || (currentDelta < 0 && relativeMotion > 0);

  return closingGap ? "applying" : "separating";
}
