/**
 * Sabian Symbols – 360 degree meanings (public domain)
 * Source: Marc Edmund Jones & Elsie Wheeler (1925)
 * Each symbol is an archetypal image for the specific degree.
 *
 * Verified/rebuilt 2026-07-22 — previous version had Pisces 19-30 stuck
 * in a repeating 4-line loop and Aquarius 19-30 duplicated verbatim from
 * Libra. All 360 entries below are unique.
 */

export const SABIAN_SYMBOLS: Record<string, string[]> = {
  Aries: [
    "A woman just risen from the sea; a seal embraces her.",
    "A comedian reveals human nature.",
    "The cameo profile of a man, suggesting the shape of his country.",
    "Two lovers strolling on a secluded walk.",
    "A triangle with wings.",
    "A square, with one of its sides brightly illumined.",
    "A man succeeds in expressing himself simultaneously in two realms.",
    "A large woman's hat with streamers blown by an east wind.",
    "A crystal gazer.",
    "A teacher gives new symbolic forms to traditional images.",
    "The ruler of a nation.",
    "A triangularly shaped flight of wild geese.",
    "An unexploded bomb reveals an unsuccessful social protest.",
    "A serpent coiling near a man and a woman.",
    "An Indian weaving a ceremonial blanket.",
    "Nature spirits are seen at work in the light of sunset.",
    "Two dignified spinsters sitting in silence.",
    "An empty hammock stretched between two trees.",
    "The 'Magic Carpet' of oriental imagery.",
    "A young girl feeding birds in winter.",
    "A pugilist enters the ring.",
    "The gate to the garden of all fulfilled desires.",
    "A pregnant woman in light summer dress.",
    "Blown inward by the wind, curtains take the shape of a cornucopia.",
    "The possibility for man to gain experience at two levels of being.",
    "A man possessed of more gifts than he can hold.",
    "Through imagination a lost opportunity is regained.",
    "A large audience confronts a performer who disappointed its expectations.",
    "The music of the spheres.",
    "A duck pond and its brood.",
  ],
  Taurus: [
    "A clear mountain stream.",
    "An electrical storm.",
    "Natural steps lead to a lawn of clover in bloom.",
    "The pot of gold at the end of the rainbow.",
    "A widow at an open grave.",
    "A cantilever bridge across a deep gorge.",
    "The woman of Samaria at the ancestral well.",
    "A sleigh on land uncovered by snow.",
    "A fully decorated Christmas tree.",
    "A red cross nurse.",
    "A woman watering flowers in her garden.",
    "A young couple window shopping.",
    "A porter carrying heavy baggage.",
    "On the beach, children play while shellfish grope at the edge of the water.",
    "Head covered against the cold, a man braves a storm in a rakish silk hat.",
    "An old teacher fails to interest his pupils in traditional knowledge.",
    "A symbolical battle between 'swords' and 'torches.'",
    "A woman airing an old bag through the open window of her room.",
    "A new continent rising out of the ocean.",
    "Wisps of winglike clouds streaming across the sky.",
    "A finger pointing to a line in an open book.",
    "A white dove flying over troubled waters.",
    "A jewelry shop filled with valuable gems.",
    "An Indian warrior riding fiercely, human scalps hanging from his belt.",
    "A vast public park.",
    "A Spanish gallant serenades his beloved.",
    "An old Indian woman selling the artifacts of her tribe to passersby.",
    "A woman past her 'change of life' experiences a new love.",
    "Two cobblers working at a table.",
    "A peacock parading on the terrace of an old castle.",
  ],
  Gemini: [
    "A glass-bottomed boat reveals undersea wonders.",
    "Santa Claus furtively filling stockings hung by the fireplace.",
    "The Garden of the Tuileries in Paris.",
    "Holly and mistletoe reawaken old memories of Christmas.",
    "A revolutionary magazine asking for action.",
    "Workmen drilling for oil.",
    "A well with bucket and rope under the shade of majestic trees.",
    "Aroused strikers surround a factory.",
    "A quiver filled with arrows.",
    "An airplane performing a nose dive.",
    "Newly opened lands offer the pioneer new opportunities for experience.",
    "A woman fights for her independence in the city.",
    "A famous pianist giving a concert performance.",
    "Bridging space and social distinctions, two men communicate telepathically.",
    "Two children talking to each other, exchanging their knowledge.",
    "A woman in an emotional speech dramatizes her cause.",
    "The head of a robust youth changes into that of a mature thinker.",
    "Two men converse in their native tongue in a foreign city.",
    "A large archaic volume reveals a traditional wisdom.",
    "A modern cafeteria displays an abundance of food from various regions.",
    "A tumultuous labor demonstration.",
    "Dancing couples in a harvest festival.",
    "Three fledglings in a nest high in a tree.",
    "Children skating over a frozen village pond.",
    "A gardener trimming large palm trees.",
    "Frost-covered trees against winter skies.",
    "A gypsy emerging from the forest wherein her tribe is encamped.",
    "Through bankruptcy, an overburdened individual gets a chance to begin again.",
    "The first mockingbird of spring.",
    "A parade of bathing beauties before large beach crowds.",
  ],
  Cancer: [
    "On a ship the sailors lower an old flag and raise a new one.",
    "A man on a magic carpet hovers over a large area of land.",
    "A man bundled in fur leads a shaggy deer.",
    "A cat arguing with a mouse.",
    "At a railroad crossing, an automobile is wrecked by a train.",
    "Game birds feathering their nests.",
    "Two nature spirits dancing under the moonlight.",
    "A group of rabbits dressed in human clothes walk as if on parade.",
    "A small naked girl bends over a pond trying to catch a fish.",
    "A large diamond in the first stages of the cutting process.",
    "A clown caricaturing well-known personalities.",
    "A woman nursing a baby whose aura reveals him as a great soul reborn.",
    "A hand with a prominent thumb is held out for study.",
    "A very old man facing a vast dark space to the northeast.",
    "In a sumptuous dining hall guests relax after a huge banquet.",
    "A man studies a mandala with the help of a very ancient book.",
    "The unfoldment of multilevel potentialities issuing from an original germ.",
    "A hen scratching the ground to find nourishment for her progeny.",
    "A priest performing a marriage ceremony.",
    "Venetian gondoliers giving a serenade.",
    "A famous singer proves her virtuosity during an operatic performance.",
    "A young woman awaiting a sailboat.",
    "The meeting of a literary society.",
    "A woman and two men castaway on a small island of the south seas.",
    "A willful man is overshadowed by a descent of superior power.",
    "Guests are reading in the library of a luxurious home.",
    "A violent storm in a canyon filled with expensive homes.",
    "A woman introduces her lover to her assembled tribe.",
    "A Greek muse weighing newborn twins in golden scales.",
    "A daughter of the American Revolution.",
  ],
  Leo: [
    "Blood rushes to a man's head as his vital energies are mobilized by ambition.",
    "An epidemic of mumps.",
    "A middle-aged woman, her long hair flowing, in a youthful garment.",
    "A formally dressed elderly man stands near trophies from a hunt.",
    "Rock formations tower over a deep canyon.",
    "A conservative, old-fashioned lady is confronted by a rebellious girl.",
    "The constellations of stars shine brilliantly in the night sky.",
    "An activist spreads his revolutionary ideals.",
    "Glass blowers shape beautiful vases with their controlled breathing.",
    "Early morning dew sparkles as sunlight floods the field.",
    "Children play on a swing hanging from the branches of a huge oak tree.",
    "An evening party of adults on a lawn illumined by fancy lanterns.",
    "An old sea captain rocking himself on the porch of his cottage.",
    "A human soul seeking opportunities for outward manifestation.",
    "A pageant with spectacular floats moves along a crowded street.",
    "The storm ended, all nature rejoices in brilliant sunshine.",
    "A volunteer church choir singing religious hymns.",
    "A chemist conducts an experiment for his students.",
    "A houseboat party.",
    "Native dancers perform a ritual to the sun.",
    "Intoxicated chickens dizzily flap their wings trying to fly.",
    "A carrier pigeon fulfilling its mission.",
    "In a circus the bareback rider displays her dangerous skill.",
    "Totally intent on inner spiritual attainment, a man neglects his appearance.",
    "A large camel is seen crossing a vast and forbidding desert.",
    "After the heavy storm, a rainbow.",
    "The luminescence of dawn in the eastern sky.",
    "Many little birds on a limb of a big tree.",
    "A mermaid emerges from the ocean waves ready for rebirth in human form.",
    "An unsealed letter.",
  ],
  Virgo: [
    "In a portrait, the significant features of a man's head are emphasized.",
    "A large white cross dominates the landscape.",
    "Two guardian angels.",
    "Black and white children play together happily.",
    "A man becomes aware of nature spirits and unseen spiritual agencies.",
    "A merry-go-round.",
    "A harem.",
    "A five-year-old child takes a first dancing lesson.",
    "An expressionist painter at work.",
    "Two heads looking out and beyond the shadows.",
    "In her baby a mother sees her deep longing for a son answered.",
    "After the wedding, the groom snatches the veil away from his bride.",
    "A powerful statesman overcomes a state of political hysteria.",
    "An aristocratic family tree.",
    "A fine lace handkerchief, heirloom from valorous ancestors.",
    "In the zoo, children are brought face to face with an orangutan.",
    "A volcanic eruption.",
    "An Ouija board.",
    "A swimming race.",
    "A caravan of cars headed to the west coast.",
    "A girls' basketball team.",
    "A royal coat of arms enriched with precious stones.",
    "A lion tamer displays his skill and character.",
    "Mary and her little lamb.",
    "A flag at half-mast in front of a public building.",
    "A boy with a censer serves the priest near the altar.",
    "A group of aristocratic ladies meet ceremonially at a court's function.",
    "A baldheaded man who has seized power.",
    "A seeker after occult knowledge reads an ancient scroll that illumines his mind.",
    "Totally intent on completing an immediate task, a man is deaf to any allurement.",
  ],
  Libra: [
    "A butterfly displays the beauty of its wings, its body impaled by a fine dart.",
    "The transmutation of past experience into the seed-realizations of creative spirit.",
    "The dawn of a new day reveals everything changed.",
    "Around a campfire a group of young people sit in spiritual communion.",
    "A man reveals to his students the foundation of an inner knowledge.",
    "A man watches his ideals taking concrete form before his inner vision.",
    "A woman feeding chickens and protecting them from the hawks.",
    "A blazing fireplace in a deserted home.",
    "Three 'old masters' hanging on the wall of a special room in an art gallery.",
    "Having passed through narrow rapids, a canoe reaches calm waters.",
    "A professor peering over his glasses at his students.",
    "Miners are surfacing from a deep coal mine.",
    "Children blowing soap bubbles.",
    "In the heat of the noon hour a man takes a siesta.",
    "Circular paths.",
    "After a storm a boat landing stands in need of reconstruction.",
    "A retired sea captain watches ships entering and leaving the harbor.",
    "Two men placed under arrest.",
    "A gang of robbers in hiding.",
    "A rabbi performing his duties.",
    "A Sunday crowd enjoying the beach.",
    "A child giving birds a drink at a fountain.",
    "A rooster's voice heralds sunrise.",
    "A butterfly with a third wing on its left side.",
    "The sight of an autumn leaf brings a pilgrim sudden revelation of life and death.",
    "An eagle and a large white dove change into each other.",
    "An airplane sails high in the clear sky.",
    "A man becomes aware of spiritual forces surrounding and assisting him.",
    "Mankind's vast and enduring effort to reach for transferable knowledge.",
    "Three mounds of knowledge on a philosopher's head.",
  ],
  Scorpio: [
    "A crowded sightseeing bus on a city street.",
    "A delicate bottle of perfume lies broken, releasing its fragrance.",
    "A house-raising party in a small village enlists the neighbors' cooperation.",
    "A youth carries a lighted candle in a devotional ritual.",
    "A massive rocky shore resists the pounding of the sea.",
    "The gold rush tears men away from their native soil.",
    "Deep-sea divers.",
    "A calm lake bathed in moonlight.",
    "A dentist at work.",
    "A fellowship supper reunites old comrades.",
    "A drowning man is being rescued.",
    "An official embassy ball.",
    "An inventor performs a laboratory experiment.",
    "A telephone lineman at work installing new connections.",
    "Children playing around five mounds of sand.",
    "A girl's face breaking into a smile.",
    "A woman, fecundated by her own spirit, is 'great with child.'",
    "A path through woods brilliant with multicolored splendor.",
    "A parrot repeats the conversation he has overheard.",
    "A woman draws away two dark curtains closing a sacred pathway.",
    "Obeying his conscience, a soldier resists orders.",
    "Hunters shooting wild ducks.",
    "A rabbit metamorphoses into a nature spirit.",
    "After a Sermon on the Mount, crowds are returning home.",
    "An X-ray photograph.",
    "American Indians making camp after moving into a new territory.",
    "A military band marches noisily on through the city streets.",
    "The king of the fairies approaching his domain.",
    "A woman pleads to the chief for the lives of her children.",
    "Children in Halloween costumes indulge in various pranks.",
  ],
  Sagittarius: [
    "Retired army veterans gather to reawaken old memories.",
    "White-capped waves display the power of wind over sea.",
    "Two men playing chess.",
    "A little child learns to walk with the encouragement of his parents.",
    "An old owl sits alone on the branch of a large tree.",
    "A game of cricket.",
    "Cupid knocks at the door of a human heart.",
    "Within the depths of the earth new elements are being formed.",
    "A mother leads her small child step by step up a steep stairway.",
    "A theatrical representation of a golden-haired goddess of opportunity.",
    "In an archaic temple, a lamp burns in a container shaped like a human body.",
    "A flag turns into an eagle; the eagle into a rooster saluting the dawn.",
    "A widow's past is brought to light.",
    "The great pyramid and the sphinx.",
    "A ground hog looking for its shadow on Ground Hog Day.",
    "Sea gulls fly around a ship in expectation of food.",
    "An Easter sunrise service draws a large crowd.",
    "Children playing on the beach, their heads protected by sunbonnets.",
    "Pelicans, menaced by man's refuse, seek safer areas to raise their young.",
    "In an old northern village, men cut ice from a frozen pond for summer use.",
    "A child and a dog wearing borrowed eyeglasses.",
    "A Chinese laundry.",
    "A group of immigrants fulfill the requirements to enter the new country.",
    "A bluebird perched on the gate of a cottage.",
    "A chubby boy on a hobby-horse.",
    "A flag bearer in a battle.",
    "A sculptor at his work.",
    "An old bridge over a beautiful stream is still in constant use.",
    "A fat boy mowing the lawn of his house on an elegant suburban street.",
    "The pope blessing the faithful.",
  ],
  Capricorn: [
    "An Indian chief claims power from the assembled tribe.",
    "Three rose windows in a Gothic church, one damaged by war.",
    "A human soul, eager for new experience, seeks embodiment.",
    "A group of people outfit a large canoe at the start of a journey by water.",
    "Indians on the warpath; some row a canoe, others perform a war dance.",
    "Ten logs lie under an archway leading to darker woods.",
    "A veiled prophet speaks, seized by the power of a god.",
    "In a sunlit home domesticated birds sing joyously.",
    "An angel carrying a harp.",
    "An albatross feeding from the hand of a sailor.",
    "A large group of pheasant on a private estate.",
    "An illustrated lecture on natural science reveals little-known aspects of life.",
    "A fire worshipper meditates on the ultimate realities of existence.",
    "An ancient bas-relief carved in granite remains a witness to a lost culture.",
    "In a hospital, the children's ward is filled with toys.",
    "School grounds filled with boys and girls in gymnasium suits.",
    "A repressed woman finds a psychological release in nudism.",
    "The Union Jack flies from a British warship.",
    "A five-year-old child carrying a bag filled with groceries.",
    "A hidden choir is singing during a religious service.",
    "A relay race.",
    "By accepting defeat gracefully, a general reveals nobility of character.",
    "A soldier receiving two awards for bravery in combat.",
    "A woman entering a convent.",
    "A store filled with precious oriental rugs.",
    "A nature spirit dancing in the iridescent mist of a waterfall.",
    "Pilgrims climbing the steep steps leading to a mountain shrine.",
    "A large aviary.",
    "A woman reading tea leaves.",
    "A secret meeting of men responsible for executive decisions in world affairs.",
  ],
  Aquarius: [
    "An old adobe mission in California.",
    "An unexpected thunderstorm.",
    "A deserter from the navy.",
    "A healer demonstrates his healing powers.",
    "A council of ancestors is seen implementing the efforts of a young leader.",
    "A masked figure performs ritualistic acts in a mystery play.",
    "A child is seen being born out of an egg.",
    "Beautifully gowned wax figures on display.",
    "A flag is seen turning into an eagle.",
    "A man who embodied a popular ideal realizes he is not that ideal.",
    "During a silent hour, a man receives a new inspiration that may change his life.",
    "On a vast staircase stand people of different types, graduated upward.",
    "A barometer.",
    "A train entering a tunnel.",
    "Two lovebirds sitting on a fence and singing happily.",
    "A big businessman at his desk.",
    "A watchdog stands guard, protecting his master and his possessions.",
    "A man's secret motives are being publicly unmasked.",
    "A forest fire is subdued by water, chemicals, and sheer muscular energy.",
    "A large white dove bearing a message.",
    "A disappointed and disillusioned woman courageously faces an empty life.",
    "A rug is placed on a nursery floor so children can play in warmth and comfort.",
    "A big bear sitting down and waving all its paws.",
    "A man, having overcome his passions, teaches deep wisdom from experience.",
    "A butterfly with the right wing more perfectly formed.",
    "A garage man tests a car's battery with a hydrometer.",
    "An ancient pottery bowl filled with fresh violets.",
    "A tree felled and sawed to ensure a supply of wood for the winter.",
    "A butterfly emerging from a chrysalis.",
    "Deeply rooted in an ancient culture, a spiritual brotherhood merges into one unanimous consciousness.",
  ],
  Pisces: [
    "In a crowded marketplace farmers and middlemen display a great variety of products.",
    "A squirrel hiding from hunters.",
    "Petrified tree trunks lie broken on desert sand.",
    "Heavy car traffic on a narrow isthmus linking two seashore resorts.",
    "A church bazaar.",
    "A parade of army officers in full dress.",
    "Illumined by a shaft of light, a large cross lies on rocks surrounded by sea.",
    "A girl blowing a bugle.",
    "A jockey spurs his horse, intent on outdistancing his rivals.",
    "An aviator pursues his journey, flying through ground-obscuring clouds.",
    "Men traveling a narrow path, seeking illumination.",
    "In the sanctuary of an occult brotherhood, newly initiated members are tested.",
    "An ancient sword, used in many battles, is displayed in a museum.",
    "A lady wrapped in a large stole of fox fur.",
    "An officer instructing his men before a simulated assault under live fire.",
    "In the quiet of his study a creative individual experiences a flow of inspiration.",
    "An Easter parade.",
    "In a gigantic tent, villagers witness a spectacular performance.",
    "A master instructing his disciple.",
    "A table set for an evening meal.",
    "Under the watchful eye of a servant, a girl fondles a little white lamb.",
    "A prophet carrying tablets of the new law walks down the slopes of a mountain.",
    "A 'materializing' medium giving a seance.",
    "On a small island surrounded by the vast expanse of the sea, people live in close interaction.",
    "A religious organization succeeds in overcoming corrupting influences.",
    "Watching the thin moon crescent at sunset, people realize the time has come to act.",
    "The harvest moon illumines a clear autumnal sky.",
    "A fertile garden under the full moon reveals a variety of full-grown vegetables.",
    "Light breaking into many colors as it passes through a prism.",
    "A majestic rock formation resembling a face, taken as an ideal by a boy who grows to resemble it.",
  ],
};

/**
 * Get the Sabian symbol for a given sign and degree (0–30).
 * @param sign Zodiac sign name (e.g., "Aries")
 * @param degree Degree within the sign (0 to 30, fractional values floor to whole degree)
 * @returns The symbol string, or empty string if not found.
 */

export function getDegreeMeaning(sign: string, degree: number): string {
  const idx = Math.floor(degree) - 1;
  if (idx < 0 || idx >= 30) return "";

  const symbols = SABIAN_SYMBOLS[sign as keyof typeof SABIAN_SYMBOLS];
  if (!symbols) return "";

  return symbols[idx] ?? "";
}
