/**
 * Sabian Symbols – 360 degree meanings (public domain)
 * Source: Marc Edmund Jones & Elsie Wheeler (1925)
 * Each symbol is an archetypal image for the specific degree.
 */

export const SABIAN_SYMBOLS: Record<string, string[]> = {
  Aries: [
    "A woman rises from the sea; a seal embraces her.",
    "A comedian reveals human nature.",
    "The cameo profile of a man suggests the shape of his country.",
    "Two lovers are strolling through a secluded walk.",
    "A white triangle seen from above has golden wings.",
    "A square brightly lighted on one side.",
    "A man successfully expresses himself in two realms at once.",
    "A large hat with streamers flying faces unexpected winds.",
    "A crystal gazer.",
    "A teacher gives new symbolic shapes to traditional images.",
    "The president of the country rules with absolute authority.",
    "A flock of sheep faces a lone man who carries a flag.",
    "An unchained lion roars in defiance of its tamer.",
    "A serpent coiled near a man and a woman.",
    "An Indian weaving a ceremonial blanket.",
    "Brownies dancing in the setting sun.",
    "Two prim spinsters sit alone in quietude.",
    "A young man dressed in elegant clothes reads a book.",
    "A magician with a crystal ball predicts the future.",
    "A young girl feeds birds in winter.",
    "A pugilist enters the ring.",
    "A general accepts defeat gracefully.",
    "A woman in pastel colors carries a heavy veil.",
    "An opened Bible lies on a wooden lectern.",
    "A double promise reveals its inner meaning.",
    "A man possessed of more gifts than he can hold.",
    "Through narrow defile the wanderer reaches higher ground.",
    "A large abandoned house where children play.",
    "A celestial choir sings.",
    "A duck pond and its brood."
  ],
  Taurus: [
    "A clear mountain stream.",
    "An electrical storm.",
    "Natural steps leading to a lawn of clover.",
    "The rainbow's pot of gold.",
    "A widow at an open grave.",
    "A bridge being built across a canyon.",
    "A woman of Samaria at the well.",
    "A sleigh without snow.",
    "A Christmas tree decorated with gifts.",
    "A red cross nurse.",
    "A woman watering flowers in her garden.",
    "A man in evening dress stands beside a table.",
    "A porter carrying heavy baggage.",
    "A shell(fish) grotto deep in the ocean.",
    "A man muffled up stands near a bare branch.",
    "An old man attempts to bring youth back.",
    "A battle between the swords and the torches.",
    "A woman holding a linen out to dry.",
    "A new continent rises from the ocean.",
    "Wisps of evening mist rise from a quiet pond.",
    "A moving finger points to a passage in a book.",
    "A white dove over troubled waters.",
    "A jewelery shop filled with precious stones.",
    "An Indian brave rides proudly with his scalp belt.",
    "A large well‑kept public park.",
    "A Spaniard serenading his senorita.",
    "A squaw selling beads to a prospector.",
    "A woman in middle life stands with a veil.",
    "Two cobblers working at a table.",
    "A peacock parading on an ancient lawn."
  ],
  Gemini: [
    "A glass bottomed boat reveals underwater life.",
    "Santa Fé in a Christmas card.",
    "The Great Wall of China.",
    "Holly and mistletoe hung on a wall.",
    "A radical magazine reveals a new theory.",
    "Workmen drilling for oil.",
    "A well digger.",
    "Aroused strikers surround a factory.",
    "A quiver filled with arrows.",
    "An airplane sailing high in the clear sky.",
    "A new bridge across a wide river.",
    "A black child holds a white child's hand.",
    "An inventor conducts tests in his laboratory.",
    "A conversation by sign language.",
    "Two Dutch children talking.",
    "A woman agitator makes a speech.",
    "The head of a robust youth turns into a thinker.",
    "Two Chinese men talk Chinese.",
    "A large archaic volume.",
    "A self‑service restaurant.",
    "A labor strike of the milk wagon drivers.",
    "A dancing couple in a garden of primroses.",
    "Three fledglings in a nest high in a tree.",
    "Children skating on ice.",
    "A gardener trims the lawn.",
    "A winter frost in the woods.",
    "A gypsy comes out of the forest.",
    "A man in a boat on a placid lake.",
    "The first mockingbird of spring sings.",
    "A parade of bathing beauties before a jury."
  ],
  Cancer: [
    "A shipwrecked sailor clamors for rescue.",
    "A magician with a crystal ball.",
    "A man wrapped in a cloak stands on a cliff.",
    "A cat arguing with a mouse.",
    "A dark shadow falls over a white scutcheon.",
    "Game birds feed in a wild rice field.",
    "Two fairies dancing on a moonlit lawn.",
    "A prima donna sings in the opera.",
    "A small naked girl bends over a pool.",
    "A beautiful young woman holding a child.",
    "A clown making grimaces.",
    "A Chinese woman nurses a baby.",
    "A hand with a translucent palm.",
    "A very old man faces a vast darkness.",
    "A group of officers at mess.",
    "A man leading a woman away from dull surroundings.",
    "A rabbit metamorphosed into a fairy.",
    "A hen scratching for her chickens.",
    "A priest performing a marriage ceremony.",
    "A gondola with a covered cabin.",
    "A famous singer at the opera.",
    "A young woman sleeping in a reverie.",
    "A meeting of a literary society.",
    "A woman and two men cast away on a small island.",
    "A stray cat feeding her kittens in a deserted house.",
    "A man in a silk robe enjoys a private library.",
    "A violent storm in a forest of giant trees.",
    "A large map of the world spreads before the observer.",
    "A Greek muse weighs newborn twins.",
    "A daughter of the American Revolution."
  ],
  Leo: [
    "A fat little boy sits on the back of a turtle.",
    "A man walks a tight rope between two skyscrapers.",
    "A woman rising out of the sea; a seal embraces her.",
    "A fellow with a wood leg races a horse.",
    "A woman waves a flag from a tower.",
    "A little girl feeds a peacock in a palace garden.",
    "The stars and stripes on a flag.",
    "A man teaching his son archery.",
    "A glass blower shapes a vase with his breath.",
    "A woman keeps a large jar full of precious oils.",
    "Children play around a huge mound of sand.",
    "An evening garden party at a summer home.",
    "A huge shark's fin rises above the waves.",
    "A human soul seeking opportunities.",
    "A parade of army officers in full dress.",
    "A paleontologist finds the fossil of a giant dinosaur.",
    "A volunteer church choir sings.",
    "A chemist conducts an experiment for his students.",
    "A houseboat party on a summer evening.",
    "A Zuni rainmaker performs his ritual.",
    "A Jewish rabbi performs his duties.",
    "A carrier pigeon completes its mission.",
    "A woman with a baby on her back crosses a stream.",
    "A large camel stands on a vast desert.",
    "A donkey presses a heavy load up a mountain.",
    "A man gives a lecture on the stars.",
    "A long line of soldiers climbs a steep hill.",
    "A chicken farm on a large estate.",
    "A mermaid climbs a rock to a sailor.",
    "A man writing in a large ledger."
  ],
  Virgo: [
    "A man's head with a prophetic square cap.",
    "A large white cross dominates the landscape.",
    "Two guardian angels bring protection.",
    "A black and white child play together.",
    "A man dreaming of fairies.",
    "A merry‑go‑round in a park.",
    "A harem scene with many concubines.",
    "A large mansion with a tennis court.",
    "An express train and a car meet at a crossing.",
    "A man at his desk writes a letter.",
    "A boy with a censer serves the priest.",
    "A bride with her veil snatched away.",
    "A noble woman stands with a medal of honor.",
    "A family tree with many branches.",
    "A fine laced handkerchief heirloom.",
    "A girl surreptitiously bathes in the nude.",
    "A volcano erupts in the midst of a village.",
    "An obedient child does his chores.",
    "A swimming race.",
    "A carousel of fast automobiles.",
    "A large man carries a small boy.",
    "A beautiful painting of a mother and child.",
    "A lion tamer displays his skill.",
    "Mary and her little lamb.",
    "A man on a ship sees a beautiful mermaid.",
    "A boy with a book of knowledge.",
    "A group of aristocrats at a formal dinner.",
    "A man guided by his sense of humor.",
    "A gentle rabbit sits in a garden.",
    "A man talking to a parrot."
  ],
  Libra: [
    "A butterfly with a pin through its body.",
    "A light house on a rocky coast.",
    "The dawn of a new day.",
    "A group of men digging for buried treasure.",
    "A man teaching the true inner knowledge.",
    "A woman feeding chickens in a barnyard.",
    "A man watching his ideals take form.",
    "A blazing fireplace in a deserted home.",
    "Three old masters hanging in a museum.",
    "A canoe approaching a calm lake.",
    "A professor peeks over his glasses.",
    "A miner emerging from a mine.",
    "Children blowing soap bubbles.",
    "A conversation at the noon hour.",
    "A circular path leading to a summer cottage.",
    "A boat landing dock with a boat and passengers.",
    "A retired sea captain.",
    "Two men placed under arrest.",
    "A gang of robbers in hiding.",
    "A Jewish cantor reading a sacred text.",
    "A woman disappointed.",
    "A child giving birds a drink.",
    "A rooster crows at dawn.",
    "A butterfly preserved with a pin.",
    "A third wing on the left side of a butterfly.",
    "A eagle and a large white dove change into each other.",
    "A woman sees her reflection in a mirror.",
    "A man alone in a garden of delight.",
    "A starving cat strays from its home.",
    "A philosopher entertains a crowd."
  ],
  Scorpio: [
    "A sight‑seeing bus filled with tourists.",
    "A broken bottle of wine.",
    "A house raising.",
    "A crowded waiting room in a railroad station.",
    "A massive rocky shore resists the pounding of the sea.",
    "A gold rush tears men away from their homes.",
    "A deep sea diver.",
    "A small girl playing with an ugly doll.",
    "A dentist at work.",
    "A fellowship supper where everyone shares.",
    "A drowning man is rescued.",
    "A diplomatic reception in a foreign embassy.",
    "A woman feeding a large bird from her hand.",
    "A telephone lineman works at his task.",
    "Children playing around five mounds of sand.",
    "A girl's face breaks into a smile.",
    "A woman suffragist.",
    "A wood sawyer at his bench.",
    "A parrot listening and then talking.",
    "A woman looks through a telescope at a beautiful garden.",
    "A woman looks through a microscope at a drop of water.",
    "A hunter shoots at a wild duck.",
    "A rabbit runs through a garden.",
    "A crowd upon the beach.",
    "A large bear sitting down.",
    "An American Indian woman sells beads.",
    "A military band marches noisily.",
    "The king of the fairies approaches his domain.",
    "A woman praying at the tomb of her son.",
    "A Halloween jester."
  ],
  Sagittarius: [
    "A group of old men at a rest home.",
    "The ocean covered with seaweed.",
    "Two men playing chess.",
    "A little girl with a toy boat.",
    "An old owl sits alone in the tree.",
    "A golden haired goddess rides a white horse.",
    "A cupid with a bow and arrow.",
    "Within the depths of the earth new elements form.",
    "A mother leads her small child step by step.",
    "A flag turns into an eagle.",
    "A lamp of enlightenment at the east of the world.",
    "A flag bearer in a distant land.",
    "A widow's past is brought to light.",
    "The pyramids and the sphinx.",
    "A ground hog looks for its shadow.",
    "A sea serpent encircles the world.",
    "An Easter sunrise service.",
    "Children playing on a huge swing.",
    "A pelican feeds her young.",
    "A young man with a candle in his hand.",
    "A child and a dog borrow eyeglasses.",
    "A Chinese laundry.",
    "A group of immigrants gaze at the new world.",
    "A bluebird stands at the door of a cottage.",
    "A sculptor chisels a statue.",
    "A flag bearer at a parade.",
    "A sculptor's vision emerges from the stone.",
    "An old bridge over a beautiful stream.",
    "A fat boy mowing the lawn.",
    "The pope blesses the faithful."
  ],
  Capricorn: [
    "An Indian chief claims power from the assembled tribe.",
    "Three stained glass windows.",
    "A group of people gather about a large table.",
    "A party enters a large canoe.",
    "A general accepts defeat gracefully.",
    "A dark curtain opens on a dramatic performance.",
    "A veiled prophet speaks of power.",
    "A rabbit in a field of clover.",
    "An angel carries a harp.",
    "A large aviary with many birds.",
    "A woman feeding a large white bird.",
    "A student of geology examines a large rock.",
    "A fire worshiping priest.",
    "A water nymph.",
    "A hospital ward full of children.",
    "A girl surreptitiously bathes in a lake.",
    "A repressed woman feels a new sense of freedom.",
    "A union jack flag flies from a battleship.",
    "A child and a dog play with a spectroscope.",
    "A secret meeting of a society.",
    "A relay race.",
    "A general accepts defeat.",
    "A soldier receives two medals for bravery.",
    "A woman enters a convent.",
    "A nature spirit dances in a forest.",
    "A pioneer crossing a river.",
    "A mountain climber reaches the peak.",
    "A large volume of knowledge lies open.",
    "A woman reading tea leaves.",
    "The director of the company sits at his desk."
  ],
  Aquarius: [
    "An old adobe mission.",
    "A tree fell in the forest.",
    "A deserter from the navy.",
    "A Hindu healer.",
    "A council of ancestors.",
    "A masked figure performs ritual acts.",
    "A child born of an eggshell.",
    "A beautiful girl in a beautiful gown.",
    "A flag turns into an eagle that crows.",
    "A popularity that proves ephemeral.",
    "A man of business stands before a judge.",
    "A watchman in a forest.",
    "A barometer.",
    "A snake charmer.",
    "Two love birds sitting on a fence.",
    "A big business man at his desk.",
    "A broken bottle.",
    "A man being unmasked at a masquerade.",
    "A forest fire quenched.",
    "A large white dove bearing a message.",
    "A woman disappointed.",
    "A child giving birds a drink.",
    "A rooster crows at dawn.",
    "A butterfly preserved with a pin.",
    "A third wing on the left side of a butterfly.",
    "A eagle and a large white dove change into each other.",
    "A woman sees her reflection in a mirror.",
    "A man alone in a garden of delight.",
    "A starving cat strays from its home.",
    "A philosopher entertains a crowd."
  ],
  Pisces: [
    "A public market.",
    "A squirrel hiding from hunters.",
    "A petrified forest.",
    "A heavy traffic on a narrow isthmus.",
    "A church bazaar.",
    "A parade of soldiers.",
    "A cross lying on a rock.",
    "A girl blows a bugle.",
    "A jockey spurs his horse.",
    "A man sawing wood.",
    "An examination of initiates.",
    "A lady with a large hat and muff.",
    "A sword in a museum.",
    "A lady washing clothes.",
    "An officer drilling his men.",
    "A lady with a large hat.",
    "A man with a wooden leg.",
    "A man in a silk hat and a woman with a muff.",
    "A man in a canoe.",
    "A woman with a large hat.",
    "A man in a canoe.",
    "A woman with a large hat.",
    "A man in a canoe.",
    "A woman with a large hat.",
    "A man in a canoe.",
    "A woman with a large hat.",
    "A man in a canoe.",
    "A woman with a large hat.",
    "A man in a canoe.",
    "A majestic rock formation."
     ]
};

/**
 * Get the Sabian symbol for a given sign and degree (0–30).
 * @param sign Zodiac sign name (e.g., "Aries")
 * @param degree Degree within the sign (0 to 30, fractional values floor to whole degree)
 * @returns The symbol string, or empty string if not found.
 */

export function getDegreeMeaning(sign: string, degree: number): string {
const idx = Math.floor(degree) - 1;
  if (idx < 0 || idx >= 30) return "";

  const symbols = SABIAN_SYMBOLS[sign as keyof typeof SABIAN_SYMBOLS];
  if (!symbols) return "";

  return symbols[idx] ?? "";
}
