import type { ChartResult, ChartRow } from "../../../server/astronomy";

const colors: Record<string, string> = { Sun: "#fbbf24", Moon: "#e2e8f0", Mercury: "#67e8f9", Venus: "#f9a8d4", Mars: "#fb7185", Jupiter: "#c4b5fd", Saturn: "#94a3b8", Uranus: "#5eead4", Neptune: "#818cf8", Pluto: "#f0abfc", "North Node": "#34d399", "South Node": "#f97316" };
function point(longitude: number, radius: number, center: number) { const angle = (longitude - 90) * Math.PI / 180; return { x: center + Math.cos(angle) * radius, y: center + Math.sin(angle) * radius }; }
function Dot({ row, radius, center, labelRadius, transit = false }: { row: ChartRow; radius: number; center: number; labelRadius: number; transit?: boolean }) { const p = point(row.longitude, radius, center); const label = point(row.longitude, labelRadius, center); const color = colors[row.name] ?? (transit ? "#22d3ee" : "#c4b5fd"); return <g><line x1={center} y1={center} x2={p.x} y2={p.y} stroke={color} strokeOpacity=".16" strokeWidth="1"/><circle cx={p.x} cy={p.y} r={transit ? 5 : 6} fill={color} stroke="#090d19" strokeWidth="2"/><text x={label.x} y={label.y} fill={color} fontSize="10" textAnchor="middle" dominantBaseline="middle" fontFamily="DM Sans, sans-serif">{row.name === "North Node" ? "NN" : row.name === "South Node" ? "SN" : row.name.slice(0, 2)}</text></g>; }
export function ChartWheel({ chart }: { chart: ChartResult }) {
  const size = 620; const center = size / 2; const natalRadius = 220; const transitRadius = 178; const houses = chart.houses.slice(0, 12); const transits = chart.transits.filter(row => ["Sun", "Moon", "Mercury", "Venus", "Mars", "Jupiter", "Saturn", "Uranus", "Neptune", "Pluto"].includes(row.name));
  return <div className="rounded-2xl border border-cyan-200/10 bg-[#0a0e1b] p-3 sm:p-5"><div className="mb-3 flex flex-wrap items-center justify-between gap-2"><div><div className="text-xs uppercase tracking-[0.22em] text-cyan-300">Visual chart map</div><div className="mt-1 text-sm text-slate-400">Natal placements inside · current transits outside</div></div><div className="flex gap-3 text-[11px] text-slate-400"><span><i className="mr-1 inline-block h-2 w-2 rounded-full bg-violet-300"/>Natal</span><span><i className="mr-1 inline-block h-2 w-2 rounded-full bg-cyan-300"/>Transit</span></div></div><div className="mx-auto max-w-[620px] overflow-hidden"><svg viewBox={`0 0 ${size} ${size}`} className="h-auto w-full" role="img" aria-label="Natal and transit chart wheel"><circle cx={center} cy={center} r="270" fill="#0b1020" stroke="#334155" strokeWidth="1"/><circle cx={center} cy={center} r="245" fill="none" stroke="#475569" strokeOpacity=".7"/><circle cx={center} cy={center} r="220" fill="#11172a" stroke="#64748b" strokeOpacity=".55"/><circle cx={center} cy={center} r="178" fill="#0b1020" stroke="#22d3ee" strokeOpacity=".32"/><circle cx={center} cy={center} r="128" fill="none" stroke="#475569" strokeOpacity=".45"/>{houses.map((longitude, i) => { const a = point(longitude, 220, center); const b = point(longitude, 270, center); const label = point(longitude + 15, 235, center); return <g key={`house-${i}`}><line x1={a.x} y1={a.y} x2={b.x} y2={b.y} stroke={i === 0 || i === 6 ? "#f0abfc" : "#64748b"} strokeOpacity={i === 0 || i === 6 ? ".85" : ".45"}/><text x={label.x} y={label.y} fill="#64748b" fontSize="9" textAnchor="middle">{i + 1}</text></g>; })}<line x1={center - 270} y1={center} x2={center + 270} y2={center} stroke="#334155" strokeOpacity=".5"/><line x1={center} y1={center - 270} x2={center} y2={center + 270} stroke="#334155" strokeOpacity=".5"/>{chart.movingBodies.map(row => <Dot key={`natal-${row.name}`} row={row} radius={natalRadius} center={center} labelRadius={250}/>)}<Dot row={chart.ascendant} radius={natalRadius} center={center} labelRadius={250}/><Dot row={chart.descendant} radius={natalRadius} center={center} labelRadius={250}/><Dot row={chart.northNode} radius={natalRadius} center={center} labelRadius={250}/><Dot row={chart.southNode} radius={natalRadius} center={center} labelRadius={250}/>{transits.map(row => <Dot key={`transit-${row.name}`} row={row} radius={transitRadius} center={center} labelRadius={145} transit/>)}<text x={center} y={center - 7} fill="#e2e8f0" fontSize="13" textAnchor="middle" fontFamily="Playfair Display, Georgia, serif">Firmament</text><text x={center} y={center + 14} fill="#64748b" fontSize="10" textAnchor="middle">natal + transit</text></svg></div><div className="mt-3 grid grid-cols-2 gap-2 text-[11px] text-slate-500 sm:grid-cols-4"><span>Asc {chart.ascendant.display}</span><span>Desc {chart.descendant.display}</span><span>NN {chart.northNode.display}</span><span>SN {chart.southNode.display}</span></div></div>;
}
