import { useState } from "react";
import { BookOpen, Brain, Check, Compass, Loader2, MessageCircle, Sparkles, WandSparkles } from "lucide-react";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Streamdown } from "streamdown";
import { trpc } from "@/lib/trpc";
import { AIChatBox, type Message } from "@/components/AIChatBox";
import type { ChartResult } from "../../../server/astronomy";

type ReadingMode = "natal" | "transit" | "combined";
type Interpretation = { intelligence: string; reading: string; generatedAt: string };
const modes: Array<{ value: ReadingMode; label: string; short: string; description: string }> = [
  { value: "natal", label: "Natal chart", short: "The foundation", description: "Your enduring birth-chart story" },
  { value: "transit", label: "Transit reading", short: "The present chapter", description: "What the selected moment is activating" },
  { value: "combined", label: "Natal + transit", short: "The full picture", description: "Your foundation meeting the present moment" },
];

const prose = "prose prose-invert max-w-none prose-headings:font-serif prose-headings:font-medium prose-headings:text-white prose-headings:tracking-tight prose-h2:mb-4 prose-h2:mt-2 prose-h2:text-2xl sm:prose-h2:text-3xl prose-h3:mb-2 prose-h3:mt-7 prose-h3:text-lg prose-h3:text-cyan-100 prose-p:my-4 prose-p:text-[15px] prose-p:leading-8 prose-p:text-slate-300 prose-li:my-2 prose-li:text-slate-300 prose-strong:text-cyan-100 prose-blockquote:border-cyan-300/40 prose-blockquote:text-slate-300";

export function InterpretationPanel({ chart }: { chart: ChartResult }) {
  const [mode, setMode] = useState<ReadingMode>("combined");
  const [interpretation, setInterpretation] = useState<Interpretation | null>(null);
  const [messages, setMessages] = useState<Message[]>([]);
  const generate = trpc.interpretation.generate.useMutation({ onSuccess: data => { setInterpretation(data); setMessages([{ role: "assistant", content: `Your ${mode === "natal" ? "natal chart" : mode === "transit" ? "transit" : "combined"} reading is ready. I can help you sit with any part of it.` }]); } });
  const chat = trpc.interpretation.followUp.useMutation({ onSuccess: answer => setMessages(current => [...current, { role: "assistant", content: answer }]) });
  const run = () => { setInterpretation(null); setMessages([]); generate.mutate({ chart, mode }); };
  const send = (question: string) => { if (!interpretation) return; const next = [...messages, { role: "user" as const, content: question }]; setMessages(next); chat.mutate({ chart, interpretation, mode, history: next.filter((message): message is Extract<Message, { role: "user" | "assistant" }> => message.role !== "system"), question }); };
  const selected = modes.find(item => item.value === mode)!;

  return <section className="mt-10 space-y-7 border-t border-white/10 pt-10 sm:mt-14 sm:pt-14">
    <div className="mx-auto max-w-4xl text-center"><div className="mb-3 flex items-center justify-center gap-2 text-xs uppercase tracking-[0.28em] text-cyan-300"><BookOpen className="h-4 w-4"/> Your personal reading</div><h2 className="font-serif text-4xl leading-tight text-white sm:text-5xl">A story written in your sky</h2><p className="mx-auto mt-4 max-w-2xl text-sm leading-7 text-slate-400 sm:text-base">This is a private self-knowledge profile, not a data dump. Choose a layer and let the guide unfold the patterns, needs, gifts, defenses, relationships, and growth edges you may recognize in your own life.</p></div>
    <Card className="mx-auto max-w-5xl overflow-hidden border-cyan-200/15 bg-gradient-to-br from-cyan-100/[0.08] via-white/[0.035] to-violet-200/[0.06] text-slate-100 shadow-2xl shadow-cyan-950/20"><CardContent className="p-4 sm:p-6"><div className="mb-4 flex items-center gap-3 text-sm text-slate-300"><Compass className="h-4 w-4 text-cyan-300"/><span>What would you like to read?</span></div><div className="grid gap-3 md:grid-cols-3">{modes.map(item => <button key={item.value} type="button" onClick={() => { setMode(item.value); setInterpretation(null); setMessages([]); }} className={`group rounded-2xl border p-4 text-left transition-all sm:p-5 ${mode === item.value ? "border-cyan-300/60 bg-cyan-200/10 shadow-lg shadow-cyan-950/20" : "border-white/10 bg-black/10 hover:border-white/25 hover:bg-white/[0.06]"}`}><div className="flex items-start justify-between gap-3"><div><div className="text-base font-semibold text-white">{item.label}</div><div className="mt-1 text-xs uppercase tracking-[0.16em] text-cyan-200/70">{item.short}</div></div>{mode === item.value && <span className="rounded-full bg-cyan-300/15 p-1 text-cyan-200"><Check className="h-4 w-4"/></span>}</div><div className="mt-4 text-sm leading-6 text-slate-400">{item.description}</div></button>)}</div></CardContent></Card>
    {!interpretation && <div className="mx-auto max-w-5xl"><Button onClick={run} disabled={generate.isPending} className="h-12 w-full rounded-xl bg-cyan-400 text-sm font-semibold text-slate-950 shadow-lg shadow-cyan-950/30 hover:bg-cyan-300">{generate.isPending ? <Loader2 className="mr-2 h-4 w-4 animate-spin"/> : <WandSparkles className="mr-2 h-4 w-4"/>}{generate.isPending ? "Listening to the chart…" : `Begin your ${selected.label.toLowerCase()}`}</Button></div>}
    {generate.error && <div className="mx-auto max-w-5xl rounded-2xl border border-rose-300/20 bg-rose-400/10 p-5 text-sm leading-6 text-rose-100"><div className="font-medium">The reading could not be completed.</div><div className="mt-1 text-rose-200/80">{generate.error.message}</div><Button variant="outline" onClick={run} className="mt-4 border-rose-200/30 bg-transparent text-rose-100 hover:bg-rose-100/10">Try again</Button></div>}
    {interpretation ? <div className="mx-auto max-w-5xl space-y-6">
      <div className="flex flex-col gap-3 border-b border-white/10 pb-5 sm:flex-row sm:items-end sm:justify-between"><div><div className="text-xs uppercase tracking-[0.24em] text-cyan-300">{selected.short}</div><h3 className="mt-2 font-serif text-3xl text-white sm:text-4xl">Your {selected.label.toLowerCase()}</h3><p className="mt-2 text-sm text-slate-400">A reading for {chart.input.location}, held with care and interpreted from the calculated chart.</p></div><Button variant="outline" onClick={run} disabled={generate.isPending} className="border-white/15 bg-white/[0.04] text-slate-200 hover:bg-white/[0.09]">{generate.isPending ? <Loader2 className="mr-2 h-4 w-4 animate-spin"/> : <Sparkles className="mr-2 h-4 w-4"/>}Read again</Button></div>
      <Card className="overflow-hidden border-cyan-200/15 bg-gradient-to-br from-cyan-100/[0.07] to-white/[0.025] text-slate-100"><CardHeader className="border-b border-cyan-200/10 px-5 py-5 sm:px-7"><CardTitle className="flex items-center gap-3 font-serif text-2xl text-white"><Brain className="h-5 w-5 text-cyan-300"/>At a glance</CardTitle><p className="text-sm text-slate-400">The central shape of what the chart is saying before we walk through the story.</p></CardHeader><CardContent className={`px-5 py-6 sm:px-8 sm:py-8 ${prose}`}><Streamdown>{interpretation.intelligence}</Streamdown></CardContent></Card>
      <Card className="overflow-hidden border-white/10 bg-white/[0.035] text-slate-100"><CardHeader className="border-b border-white/10 px-5 py-5 sm:px-7"><CardTitle className="flex items-center gap-3 font-serif text-2xl text-white"><Sparkles className="h-5 w-5 text-violet-300"/>The reading</CardTitle><p className="text-sm text-slate-400">Move slowly through this. Keep what recognizes your life; question what does not.</p></CardHeader><CardContent className={`px-5 py-7 sm:px-8 sm:py-10 ${prose}`}><Streamdown>{interpretation.reading}</Streamdown></CardContent></Card>
      <Card className="overflow-hidden border-violet-200/15 bg-violet-100/[0.035] text-slate-100"><CardHeader className="border-b border-violet-200/10 px-5 py-5 sm:px-7"><CardTitle className="flex items-center gap-3 font-serif text-2xl text-white"><MessageCircle className="h-5 w-5 text-violet-300"/>Ask the guide</CardTitle><p className="text-sm text-slate-400">Stay with this {selected.label.toLowerCase()} and ask about any part that needs a closer look.</p></CardHeader><CardContent className="p-0"><AIChatBox messages={messages} onSendMessage={send} isLoading={chat.isPending} height="420px" placeholder="Ask about your reading…" emptyStateMessage="Ask about a pattern, placement, or passage" suggestedPrompts={["Tell me more about the central theme.", "How might this show up in relationships?", "What is the honest lesson here?", "What should I pay attention to in daily life?"]}/></CardContent></Card>
      {chat.error && <p className="text-sm text-rose-300">{chat.error.message}</p>}
    </div> : <div className="mx-auto max-w-3xl rounded-2xl border border-dashed border-cyan-200/15 bg-cyan-100/[0.02] p-8 text-center text-sm leading-7 text-slate-400 sm:p-10">Choose a reading above. The chart will first offer a clear orientation, then unfold into a personal narrative with chapters, reflection points, and practical guidance.</div>}
  </section>;
}
